version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rena0531/go-test-app
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: go test -covermode=count -coverprofile=coverage.out
      - run: $GOPATH/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_REPO_TOKEN
