version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rena0531/go-test-app
    steps:
      - checkout
      - run: go mod download
      - run: go test
